"""Regenerate synthetic SQL input and expected JSON, or verify checked-in copies."""

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from qdb_impact.model import SEARCH_COLUMNS, analyze


def literal(value):
    return "NULL" if value is None else "N'" + value.replace("'", "''") + "'"


def render_sql(data):
    columns = ("Description", *SEARCH_COLUMNS, "Position")
    lines = [
        "-- Generated by tools/build_demo.py from examples/synthetic_catalog.json.",
        "-- Synthetic data only. Run in the same session as 10_impact_report.sql.",
        "SET NOCOUNT ON;",
        "DROP TABLE IF EXISTS #PortfolioNotes;",
        "DROP TABLE IF EXISTS #PortfolioApplications;",
        "CREATE TABLE #PortfolioNotes ([Note] nvarchar(max), [MappingStatus] nvarchar(max));",
        "INSERT INTO #PortfolioNotes ([Note], [MappingStatus]) VALUES",
        ",\n".join("    (" + literal(n["Note"]) + ", " + literal(n.get("MappingStatus")) + ")" for n in data["notes"]) + ";",
        "CREATE TABLE #PortfolioApplications (",
        ",\n".join("    [" + c + "] nvarchar(max) NULL" for c in columns),
        ");",
    ]
    for application in data["applications"]:
        keys = [c for c in columns if c in application]
        lines += [
            "INSERT INTO #PortfolioApplications (" + ", ".join("[" + c + "]" for c in keys) + ")",
            "VALUES (" + ", ".join(literal(application[c]) for c in keys) + ");",
        ]
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = json.loads((ROOT / "examples/synthetic_catalog.json").read_text(encoding="utf-8"))
    artifacts = {
        ROOT / "sql/00_demo_inputs.sql": render_sql(data),
        ROOT / "examples/expected_report.json": json.dumps(analyze(data["notes"], data["applications"]), indent=2) + "\n",
    }
    for path, content in artifacts.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Generated artifact differs: {path.relative_to(ROOT)}")
        else:
            path.write_text(content, encoding="utf-8")
        print(f"{'Verified' if args.check else 'Generated'} {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
