-- Generated by tools/build_demo.py from examples/synthetic_catalog.json.
-- Synthetic data only. Run in the same session as 10_impact_report.sql.
SET NOCOUNT ON;
DROP TABLE IF EXISTS #PortfolioNotes;
DROP TABLE IF EXISTS #PortfolioApplications;
CREATE TABLE #PortfolioNotes ([Note] nvarchar(max), [MappingStatus] nvarchar(max));
INSERT INTO #PortfolioNotes ([Note], [MappingStatus]) VALUES
    (N'With auxiliary filter', N'Mapped'),
    (N'Two-port inlet', N'Mapped'),
    (N'Without sensor', N''),
    (N'Legacy service note', N'Mapped'),
    (N'For export package', N'');
CREATE TABLE #PortfolioApplications (
    [Description] nvarchar(max) NULL,
    [BodyStyle] nvarchar(max) NULL,
    [BrakeType] nvarchar(max) NULL,
    [CarbNumber] nvarchar(max) NULL,
    [CarbType] nvarchar(max) NULL,
    [Color] nvarchar(max) NULL,
    [Connection Type] nvarchar(max) NULL,
    [Cylinder Head Type] nvarchar(max) NULL,
    [Emissions] nvarchar(max) NULL,
    [FootNote] nvarchar(max) NULL,
    [Lead Length] nvarchar(max) NULL,
    [Note] nvarchar(max) NULL,
    [OE Number] nvarchar(max) NULL,
    [Split Year] nvarchar(max) NULL,
    [Position] nvarchar(max) NULL
);
INSERT INTO #PortfolioApplications ([Description], [BodyStyle], [Connection Type], [FootNote], [Note])
VALUES (N'Fuel Valve', N'With auxiliary filter', N'Two-port inlet', N'Without sensor', N'With auxiliary filter');
INSERT INTO #PortfolioApplications ([Description], [Note])
VALUES (N'Fuel Valve', N'With auxiliary filter');
INSERT INTO #PortfolioApplications ([Description], [Note])
VALUES (N'Fuel Sensor', N'Without sensor');
INSERT INTO #PortfolioApplications ([Description], [Note])
VALUES (N'Fuel Valve', N'Unlisted requirement');
INSERT INTO #PortfolioApplications ([Description], [Note])
VALUES (NULL, N'Two-port inlet');
INSERT INTO #PortfolioApplications ([Description], [Note], [Position])
VALUES (N'Service Hose', N'Unlisted requirement', N'With auxiliary filter');
